---
tenants:
  - name: ACME
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF_A
        vrf_vni: 10
        svis:
          - id: 100
            name: VLAN_100
            enabled: true
            ip_address_virtual: 10.1.100.1/24
          - id: 200
            name: VLAN_200
            enabled: true
            ip_address_virtual: 10.1.200.1/24
        bgp_peers:
          - ip_address: 10.1.5.0
            remote_as: 1
            nodes: [leaf3]
          - ip_address: 10.1.5.2
            remote_as: 1
            nodes: [leaf4]
        l3_interfaces:
          - interfaces: [Ethernet12, Ethernet12]
            ip_addresses: [10.1.5.1/31, 10.1.5.3/31]
            nodes: [leaf3, leaf4]